version: "3"

services:

  webserver:
    image: nginx:stable-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /opt/certs:/etc/nginx/certs
    networks:
      - financiera-net
      - tunimex-net
      
financiera-web:
    image: financiera-web
    container_name: financiera-web
    restart: unless-stopped
#    ports:
#     - 82:80
    networks:
      - financiera-net
      
networks:
   financiera-net:
   tunimex-net:

volumes:
  postgresql:
  postgresql_data:
  pgadmin:

